# Site settings
title: Software Developer
header-img: img/home-bg.jpg
email: paulo.ancheta@gmail.com
copyright_name: PauloAncheta
description: "Ruby, Ruby on Rails || Elixir, Phoenix"
baseurl: ""
url: "localhost:4000"
twitter_username: pauloancheta
github_username: paulo.ancheta
email_username:  paulo.ancheta@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
